debugMode: false
enableLightDirectionControls: false
lightDirectionX: 0
lightDirectionY: 0.26
lightDirectionZ: 0.96
planetPositionX: -100
planetPositionY: 0
planetPositionZ: 0
planetScale: 4
planetRotationX: 0
planetRotationY: 0
planetRotationZ: 0
shipPositionX: 5
shipPositionY: 0
shipPositionZ: 0
shipScale: 0.2
shipRotationX: 0
shipRotationY: 0
shipRotationZ: 0
